CREATE TABLE "public"."payment_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cart_details" jsonb,
    "total" numeric,
    "customer_details" jsonb,
    "status" text default 'initiated'::text,
    "stripe_session_id" text,
    "error" text
);

ALTER TABLE "public"."payment_logs" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX payment_logs_pkey ON public.payment_logs USING btree (id);

ALTER TABLE "public"."payment_logs" ADD CONSTRAINT "payment_logs_pkey" PRIMARY KEY USING INDEX "payment_logs_pkey";

-- Permite a los usuarios autenticados leer sus propios logs (opcional, ajusta según tus reglas)
CREATE POLICY "Allow individual user access to their payment logs"
ON public.payment_logs FOR SELECT
USING (auth.uid() = (customer_details->>'userId')::uuid);

-- Permite a la función del servidor insertar logs
CREATE POLICY "Allow server-side insertion of payment logs"
ON public.payment_logs FOR INSERT
WITH CHECK (true);

-- Permite a la función del servidor actualizar logs
CREATE POLICY "Allow server-side update of payment logs"
ON public.payment_logs FOR UPDATE
USING (true)
WITH CHECK (true);
