// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwklmazvdqrmuriczhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3a2xtYXp2ZHFybXVyaWN6aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTMzNDIsImV4cCI6MjA2NzAyOTM0Mn0.3eGoftaKmx7eOzjwtPBhyQMMk_1WsjIw_-1xodnMLjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});